name = "alignedgov-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
LINKS_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRrCeKNL6dLLv6mHOsdEphD1_HCKLDS1fW0IHomPRSk6OwZ7OTVuoNQ_v7OhTnFJLDEN_HIyKukwce4/pub?gid=1419865336&single=true&output=csv"
EDITORS_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRrCeKNL6dLLv6mHOsdEphD1_HCKLDS1fW0IHomPRSk6OwZ7OTVuoNQ_v7OhTnFJLDEN_HIyKukwce4/pub?gid=0&single=true&output=csv"
CONFIG_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRrCeKNL6dLLv6mHOsdEphD1_HCKLDS1fW0IHomPRSk6OwZ7OTVuoNQ_v7OhTnFJLDEN_HIyKukwce4/pub?gid=1010322382&single=true&output=csv"
ORGS_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRrCeKNL6dLLv6mHOsdEphD1_HCKLDS1fW0IHomPRSk6OwZ7OTVuoNQ_v7OhTnFJLDEN_HIyKukwce4/pub?gid=599532148&single=true&output=csv"
DEADLINES_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRrCeKNL6dLLv6mHOsdEphD1_HCKLDS1fW0IHomPRSk6OwZ7OTVuoNQ_v7OhTnFJLDEN_HIyKukwce4/pub?gid=950777082&single=true&output=csv"

[[kv_namespaces]]
binding = "KV"
id = "6b9f010f78674b9987d69ea2add08a03"

[triggers]
crons = ["0 9 1 * *"]  # 1st of each month at 9:00 AM UTC
